spring:
    application:
        name: tlias

    datasource:
        url: jdbc:mysql://localhost:3306/tlias
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Phy222205
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true

pagehelper:
    reasonable: true
    helper-dialect: mysql


